name: Deploy MkDocs to GitHub Pages with local extension

on:
  push:
    branches:
      - main  # 或你的默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ./extensions  # 安装本地 MkDocs 扩展

      - name: Build and deploy MkDocs
        run: |
          mkdocs gh-deploy --force